import { Component} from '@angular/core';
import * as $ from 'jquery';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {

  title = 'IslamicCalender';

  i = $('#inp');
  b = $('#sub');
  cities =["Ahmadpur East",
  "Ahmed Nager Chatha",
  "Ali Khan Abad",
  "Alipur",
  "Arifwala",
  "Attock",
  "Bhera",
  "Bhalwal",
  "Bahawalnagar",
  "Bahawalpur",
  "Bhakkar",
  "Burewala",
  "Chenab Nagar",
  "Chillianwala",
  "Choa Saidanshah",
  "Chakwal",
  "Chak Jhumra",
  "Chichawatni",
  "Chiniot",
  "Chishtian",
  "Chunian",
  "Dajkot",
  "Daska",
  "Davispur",
  "Darya Khan",
  "Dadu",
  "Dera Ghazi Khan",
  "Dhaular",
  "Dina",
  "Dinga",
  "Dhudial Chakwal",
  "Dipalpur",
  "Faisalabad",
  "Fateh Jang",
  "Ghakhar Mandi",
  "Gojra",
  "Gujranwala",
  "Gujrat",
  "Gujar Khan",
  "Harappa",
  "Hafizabad",
  "Haroonabad",
  "Hasilpur",
  "Haveli Lakha",
  "Islamabad",
  "Jalalpur Jattan",
  "Jampur",
  "Jaranwala",
  "Jhang",
  "Jhelum",
  "Jauharabad",
  "Jacobabad",
  "Kallar Syedan",
  "Kalabagh",
  "Karor Lal Esan",
  "Karachi",
  "Kasur",
  "Kamalia",
  "Kāmoke",
  "Khanewal",
  "Khanpur",
  "Khanqah Sharif",
  "Kharian",
  "Khushab",
  "Kot Adu",
  "Lahore",
  "Lalamusa",
  "Layyah",
  "Lawa Chakwal",
  "Liaquat Pur",
  "Lodhran",
  "Malakwal",
  "Mamoori",
  "Mailsi",
  "Mandi Bahauddin",
  "Mian Channu",
  "Mianwali",
  "Miani",
  "Multan",
  "Murree",
  "Muridke",
  "Mianwali Bangla",
  "Muzaffargarh",
  "Narowal",
  "Nankana Sahib",
  "Okara",
  "Peshawar",
  "Pakpattan",
  "Pattoki",
  "Pindi Bhattian",
  "Pind Dadan Khan",
  "Pir Mahal",
  "Qaimpur",
  "Qila Didar Singh",
  "Raiwind",
  "Rajanpur",
  "Rahim Yar Khan",
  "Rawalpindi",
  "Renala Khurd",
  "Sadiqabad",
  "Sagri",
  "Sahiwal",
  "Sambrial",
  "Samundri",
  "Sangla Hill",
  "Sarai Alamgir",
  "Sargodha",
  "Sehwan",
  "Shakargarh",
  "Sheikhupura",
  "Shujaabad",
  "Sialkot",
  "Sohawa",
  "Soianwala",
  "Siranwali",
  "Tandlianwala",
  "Talagang",
  "Taxila",
  "Thatta",
  "Toba Tek Singh",
  "Vehari",
  "Wah Cantonment",
  "Wazirabad",
  "Yazman",
  "Zafarwal"];
  

}

